### PR TITLE
Merged from upstream 14 230810 01

### PR DESCRIPTION
**Pull request by davidtranhp**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by davidtranhp** [comment]
[Build Details _ Viindoo Runbot.pdf](https://github.com/Viindoo/odoo/files/12308967/Build.Details._.Viindoo.Runbot.pdf)

**Comment by davidtranhp** [comment]
@viinbot rebuild

**Comment by davidtranhp** [comment]
@vietphuong10 soi hộ anh cái chết test này với

**Comment by vietphuong97** [comment]
> @vietphuong10 soi hộ anh cái chết test này với

vâng anh

**Comment by davidtranhp** [comment]
Thay thế bằng https://github.com/Viindoo/odoo/pull/734

**Pull request closed without merging**
