### PR TITLE
Merged from upstream 15 221016 01

### PR DESCRIPTION
**Pull request by royle-vietnam**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by royle-vietnam** [comment]
@Thanhlong2000998 ưu tiên xử lý giúp anh lỗi runbot liên quan đến `viin_partner_filter` nhé
CC @vietphuong10

**Comment by Thanhlong2000998** [comment]
> @Thanhlong2000998 ưu tiên xử lý giúp anh lỗi runbot liên quan đến `viin_partner_filter` nhé CC @vietphuong10

vâng anh

**Comment by royle-vietnam** [comment]
> viin_partner_filter

@Thanhlong2000998 có PR fix lỗi chưa em?

**Comment by Thanhlong2000998** [comment]
> 

em push PR fix rồi ạ, em có cc anh trong ticket rồi ạ @royleviindoo

**Pull request merged**
