### PR TITLE
Merged from upstream 16 230529 01

### PR DESCRIPTION
**Pull request by daonamutc1**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by daonamutc1** [comment]
Lỗi time out

**Comment by daonamutc1** [comment]
@viinbot rebuild

**Comment by davidtranhp** [comment]
@viinbot rebuild

**Comment by davidtranhp** [comment]
@viinbot rebuild

**Comment by davidtranhp** [comment]
@viinbot rebuild

**Comment by royle-vietnam** [comment]
Thay thế bởi https://github.com/Viindoo/odoo/pull/683

**Pull request closed without merging**
