### PR TITLE
Merge from upstream 15 20240111 01

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
Depends:

- [x] https://github.com/Viindoo/tvtmaaddons/pull/10109
- [x] `https://github.com/odoo/odoo/pull/149348`
- [x] https://github.com/Viindoo/erponline-enterprise/pull/2276
- [x] https://github.com/Viindoo/tvtmaaddons/pull/10155

Video: 

https://github.com/Viindoo/odoo/assets/56789189/15617451-3e72-423a-914e-1e9c1af25f5b

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by daiduongnguyen-odoo** [comment]
screenshot-runbot viindoo com-2024 01 15-15_09_40
Test sẽ được fix lần lượt ở
`https://github.com/odoo/odoo/pull/14934`
Và https://github.com/Viindoo/tvtmaaddons/pull/10109

**Comment by daiduongnguyen-odoo** [comment]
@viinbot rebuild

**Comment by royle-vietnam** [comment]
@duong77476-viindoo check lỗi runbot giúp anh nhé

**Comment by daiduongnguyen-odoo** [comment]
> @duong77476-viindoo check lỗi runbot giúp anh nhé

E có xử rồi anh ạ, chi tiết ở https://github.com/Viindoo/tvtmaaddons/pull/10155

**Pull request merged**
