### PR TITLE
Merged from upstream 14 220320 01

### PR DESCRIPTION
**Pull request by davidtranhp**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by davidtranhp** [comment]
@trinhanhngoc kiểm tra hộ anh cái này xem bị sao vì anh mới thử chạy test ở local thì không gặp lỗi. Lưu ý là có mấy PR đều bị lỗi này.
```
03/20/2022 15:02:17 | ERROR | ERROR: TestGitRepo.test_checkout_private_repo_with_valid_sshkeyTraceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 304, in _ls_remoteout = Git(self.path).ls_remote(url, env=self._get_git_env())File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 638, in <lambda>return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 1183, in _call_processreturn self.execute(call, **exec_kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 983, in executeraise GitCommandError(redacted_command, status, stderr_value, stdout_value)git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)cmdline: git ls-remote git@github.com:Viindoo/test_private.gitstderr: 'kex_exchange_identification: read: Connection reset by peerfatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists.'During handling of the above exception, another exception occurred:Traceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/tests/test_git_repo.py", line 15, in test_checkout_private_repo_with_valid_sshkeyself.private_repo.scan_for_branches()File "/opt/odoo/viindooaddons14.0/to_git/helper.py", line 28, in wrapperreturn method(self, *args, **kwargs)File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 222, in scan_for_branchesbranch_names, default_name = r._ls_remote()File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 312, in _ls_remoteraise UserError(message)odoo.exceptions.UserError: Failed to fetch data from the remote!Please make sure that you have a working network connection, the repository exists and you have the correct access rights.stderr: 'kex_exchange_identification: read: Connection reset by peerfatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists.'
-- | -- | --
03/20/2022 15:02:19 | ERROR | ERROR: TestGitRepo.test_checkout_public_repoTraceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/models/git_branch.py", line 147, in checkoutgit.fetch(url, refspec, jobs=jobs_count, env=r.repository_id._get_git_env())File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 638, in <lambda>return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 1183, in _call_processreturn self.execute(call, **exec_kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 983, in executeraise GitCommandError(redacted_command, status, stderr_value, stdout_value)git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)cmdline: git fetch --jobs=32 https://github.com/Viindoo/backend_theme 10.0:10.0stderr: 'fatal: unable to access 'https://github.com/Viindoo/backend_theme/': gnutls_handshake() failed: The TLS connection was non-properly terminated.'During handling of the above exception, another exception occurred:Traceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/tests/test_git_repo.py", line 63, in test_checkout_public_repoself.public_repo.branch_ids.checkout()File "/opt/odoo/viindooaddons14.0/to_odoo_module/models/git_branch.py", line 125, in checkoutsuper(GitBranch, self).checkout(_depth=_depth)File "/opt/odoo/viindooaddons14.0/to_git/helper.py", line 28, in wrapperreturn method(self, *args, **kwargs)File "/opt/odoo/viindooaddons14.0/to_git/models/git_branch.py", line 149, in checkoutr.repository_id.check_credentials()File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 374, in check_credentialsraise helper.MissingCredentialsError(username)odoo.addons.to_git.helper.MissingCredentialsError: None
03/20/2022 15:08:48 | ERROR | ERROR: setUpClass (odoo.addons.to_odoo_module.tests.test_access_rights.TestAccessRights)Traceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 304, in _ls_remoteout = Git(self.path).ls_remote(url, env=self._get_git_env())File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 638, in <lambda>return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 1183, in _call_processreturn self.execute(call, **exec_kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 983, in executeraise GitCommandError(redacted_command, status, stderr_value, stdout_value)git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)cmdline: git ls-remote https://github.com/Viindoo/backend_theme.gitstderr: 'fatal: unable to access 'https://github.com/Viindoo/backend_theme.git/': gnutls_handshake() failed: Error in the pull function.'During handling of the above exception, another exception occurred:Traceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_odoo_module/tests/test_access_rights.py", line 13, in setUpClasssuper(TestAccessRights, cls).setUpClass()File "/opt/odoo/viindooaddons14.0/to_odoo_module/tests/test_common.py", line 36, in setUpClasscls.test_git_branch_12 = cls.env['git.branch'].create({File "<decorator-gen-559>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 347, in _model_create_multireturn create(self, [arg])File "/opt/odoo/viindooaddons14.0/to_git_odoo_version/models/git_branch.py", line 181, in createreturn super(GitBranch, self).create(vals_list)File "<decorator-gen-171>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 348, in _model_create_multireturn create(self, arg)File "/home/q22phw15y5i7-34500/build_src/addons/mail/models/mail_thread.py", line 260, in createthreads = super(MailThread, self).create(vals_list)File "<decorator-gen-412>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 348, in _model_create_multireturn create(self, arg)File "/opt/odoo/viindooaddons14.0/viin_user_assignment_log/models/base.py", line 12, in createrecords = super(Base, self).create(vals_list)File "<decorator-gen-64>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 348, in _model_create_multireturn create(self, arg)File "/home/q22phw15y5i7-34500/build_src/odoo/addons/base/models/ir_fields.py", line 534, in createrecs = super().create(vals_list)File "<decorator-gen-13>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 348, in _model_create_multireturn create(self, arg)File "/home/q22phw15y5i7-34500/build_src/odoo/models.py", line 3876, in createrecords = self._create(data_list)File "/home/q22phw15y5i7-34500/build_src/odoo/models.py", line 4049, in _createrecords._validate_fields(name for data in data_list for name in data['stored'])File "/home/q22phw15y5i7-34500/build_src/odoo/models.py", line 1266, in _validate_fieldscheck(self)File "/opt/odoo/viindooaddons14.0/to_git/models/git_branch.py", line 63, in _check_name_vs_repositoryremote_branch_names, remote_default_branch = r.repository_id._ls_remote()File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 306, in _ls_remoteself.check_credentials()File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 374, in check_credentialsraise helper.MissingCredentialsError(username)odoo.addons.to_git.helper.MissingCredentialsError: None
```

**Comment by trinhanhngoc** [comment]
> @trinhanhngoc kiểm tra hộ anh cái này xem bị sao vì anh mới thử chạy test ở local thì không gặp lỗi. Lưu ý là có mấy PR đều bị lỗi này.
> 
> ```
> 03/20/2022 15:02:17 | ERROR | ERROR: TestGitRepo.test_checkout_private_repo_with_valid_sshkeyTraceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 304, in _ls_remoteout = Git(self.path).ls_remote(url, env=self._get_git_env())File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 638, in <lambda>return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 1183, in _call_processreturn self.execute(call, **exec_kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 983, in executeraise GitCommandError(redacted_command, status, stderr_value, stdout_value)git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)cmdline: git ls-remote git@github.com:Viindoo/test_private.gitstderr: 'kex_exchange_identification: read: Connection reset by peerfatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists.'During handling of the above exception, another exception occurred:Traceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/tests/test_git_repo.py", line 15, in test_checkout_private_repo_with_valid_sshkeyself.private_repo.scan_for_branches()File "/opt/odoo/viindooaddons14.0/to_git/helper.py", line 28, in wrapperreturn method(self, *args, **kwargs)File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 222, in scan_for_branchesbranch_names, default_name = r._ls_remote()File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 312, in _ls_remoteraise UserError(message)odoo.exceptions.UserError: Failed to fetch data from the remote!Please make sure that you have a working network connection, the repository exists and you have the correct access rights.stderr: 'kex_exchange_identification: read: Connection reset by peerfatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists.'
> -- | -- | --
> 03/20/2022 15:02:19 | ERROR | ERROR: TestGitRepo.test_checkout_public_repoTraceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/models/git_branch.py", line 147, in checkoutgit.fetch(url, refspec, jobs=jobs_count, env=r.repository_id._get_git_env())File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 638, in <lambda>return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 1183, in _call_processreturn self.execute(call, **exec_kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 983, in executeraise GitCommandError(redacted_command, status, stderr_value, stdout_value)git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)cmdline: git fetch --jobs=32 https://github.com/Viindoo/backend_theme 10.0:10.0stderr: 'fatal: unable to access 'https://github.com/Viindoo/backend_theme/': gnutls_handshake() failed: The TLS connection was non-properly terminated.'During handling of the above exception, another exception occurred:Traceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/tests/test_git_repo.py", line 63, in test_checkout_public_repoself.public_repo.branch_ids.checkout()File "/opt/odoo/viindooaddons14.0/to_odoo_module/models/git_branch.py", line 125, in checkoutsuper(GitBranch, self).checkout(_depth=_depth)File "/opt/odoo/viindooaddons14.0/to_git/helper.py", line 28, in wrapperreturn method(self, *args, **kwargs)File "/opt/odoo/viindooaddons14.0/to_git/models/git_branch.py", line 149, in checkoutr.repository_id.check_credentials()File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 374, in check_credentialsraise helper.MissingCredentialsError(username)odoo.addons.to_git.helper.MissingCredentialsError: None
> 03/20/2022 15:08:48 | ERROR | ERROR: setUpClass (odoo.addons.to_odoo_module.tests.test_access_rights.TestAccessRights)Traceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 304, in _ls_remoteout = Git(self.path).ls_remote(url, env=self._get_git_env())File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 638, in <lambda>return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 1183, in _call_processreturn self.execute(call, **exec_kwargs)File "/opt/python3.8-venv/odoo14/lib/python3.8/site-packages/git/cmd.py", line 983, in executeraise GitCommandError(redacted_command, status, stderr_value, stdout_value)git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)cmdline: git ls-remote https://github.com/Viindoo/backend_theme.gitstderr: 'fatal: unable to access 'https://github.com/Viindoo/backend_theme.git/': gnutls_handshake() failed: Error in the pull function.'During handling of the above exception, another exception occurred:Traceback (most recent call last):File "/opt/odoo/viindooaddons14.0/to_odoo_module/tests/test_access_rights.py", line 13, in setUpClasssuper(TestAccessRights, cls).setUpClass()File "/opt/odoo/viindooaddons14.0/to_odoo_module/tests/test_common.py", line 36, in setUpClasscls.test_git_branch_12 = cls.env['git.branch'].create({File "<decorator-gen-559>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 347, in _model_create_multireturn create(self, [arg])File "/opt/odoo/viindooaddons14.0/to_git_odoo_version/models/git_branch.py", line 181, in createreturn super(GitBranch, self).create(vals_list)File "<decorator-gen-171>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 348, in _model_create_multireturn create(self, arg)File "/home/q22phw15y5i7-34500/build_src/addons/mail/models/mail_thread.py", line 260, in createthreads = super(MailThread, self).create(vals_list)File "<decorator-gen-412>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 348, in _model_create_multireturn create(self, arg)File "/opt/odoo/viindooaddons14.0/viin_user_assignment_log/models/base.py", line 12, in createrecords = super(Base, self).create(vals_list)File "<decorator-gen-64>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 348, in _model_create_multireturn create(self, arg)File "/home/q22phw15y5i7-34500/build_src/odoo/addons/base/models/ir_fields.py", line 534, in createrecs = super().create(vals_list)File "<decorator-gen-13>", line 2, in createFile "/home/q22phw15y5i7-34500/build_src/odoo/api.py", line 348, in _model_create_multireturn create(self, arg)File "/home/q22phw15y5i7-34500/build_src/odoo/models.py", line 3876, in createrecords = self._create(data_list)File "/home/q22phw15y5i7-34500/build_src/odoo/models.py", line 4049, in _createrecords._validate_fields(name for data in data_list for name in data['stored'])File "/home/q22phw15y5i7-34500/build_src/odoo/models.py", line 1266, in _validate_fieldscheck(self)File "/opt/odoo/viindooaddons14.0/to_git/models/git_branch.py", line 63, in _check_name_vs_repositoryremote_branch_names, remote_default_branch = r.repository_id._ls_remote()File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 306, in _ls_remoteself.check_credentials()File "/opt/odoo/viindooaddons14.0/to_git/models/git_repository.py", line 374, in check_credentialsraise helper.MissingCredentialsError(username)odoo.addons.to_git.helper.MissingCredentialsError: None
> ```

 Mấy lỗi liên quan đến git gần đây hay xuất hiện. Em vẫn đang tìm nguyên nhân gây nên những lỗi này.

**Comment by davidtranhp** [comment]
@trinhanhngoc liệu có phải do SSH Key mình sử dụng ở runbot/saas không nhỉ? Anh thấy Github nó không hỗ trợ DSA và RSA thì nó yêu cầu phải dùng SHA-2, tức là khi gen key phải có `bits=4096`, kiểu thế này.
```
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
```

**Comment by trinhanhngoc** [comment]
> @trinhanhngoc liệu có phải do SSH Key mình sử dụng ở runbot/saas không nhỉ? Anh thấy Github nó không hỗ trợ DSA và RSA thì nó yêu cầu phải dùng SHA-2, tức là khi gen key phải có `bits=4096`, kiểu thế này.
> 
> ```
> ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
> ```

Em ko chắc. Trên máy em thường tạo key sử dụng dụng ssh-keygen mà ko thêm tham số nào, mặc định là RSA 3072 bits và chưa thấy có vấn đề gì.

**Pull request merged**
