### PR TITLE
Merged from upstream 16 230803 01

### PR DESCRIPTION
**Pull request by davidtranhp**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by davidtranhp** [comment]
@royleviindoo 

[Build Details _ Viindoo Runbot.pdf](https://github.com/Viindoo/odoo/files/12249540/Build.Details._.Viindoo.Runbot.pdf)

**Comment by royle-vietnam** [comment]
> @royleviindoo
> 
> [Build Details _ Viindoo Runbot.pdf](https://github.com/Viindoo/odoo/files/12249540/Build.Details._.Viindoo.Runbot.pdf)

@vietphuong10 xem lỗi runbot này nhé em

**Comment by vietphuong97** [comment]
> > @royleviindoo
> > [Build Details _ Viindoo Runbot.pdf](https://github.com/Viindoo/odoo/files/12249540/Build.Details._.Viindoo.Runbot.pdf)
> 
> @vietphuong10 xem lỗi runbot này nhé em

vâng anh.

**Comment by davidtranhp** [comment]
@viinbot rebuild

**Pull request merged**
