### PR TITLE
Merged from upstream 15 221201 01

### PR DESCRIPTION
**Pull request by vietphuong97**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vietphuong97** [comment]
Runbot lỗi mà sao vẫn pass hết anh ạ. @royleviindoo 

[runbot_merge_upstream.pdf](https://github.com/Viindoo/odoo/files/10130469/runbot_merge_upstream.pdf)
[runbot_merge_upstream_1.pdf](https://github.com/Viindoo/odoo/files/10130471/runbot_merge_upstream_1.pdf)
[runbot_merge_upstream_2.pdf](https://github.com/Viindoo/odoo/files/10130472/runbot_merge_upstream_2.pdf)

**Comment by vietphuong97** [comment]
kiểm tra giúp anh mấy cái test to_base nhé @hieu1211

**Comment by hieu1211** [comment]
@vietphuong10 PR này xanh real hay fake a nhỉ, có cần kiểm tra j nữa k a

**Comment by vietphuong97** [comment]
> Runbot lỗi mà sao vẫn pass hết anh ạ. @royleviindoo
> 
> [runbot_merge_upstream.pdf](https://github.com/Viindoo/odoo/files/10130469/runbot_merge_upstream.pdf) [runbot_merge_upstream_1.pdf](https://github.com/Viindoo/odoo/files/10130471/runbot_merge_upstream_1.pdf) [runbot_merge_upstream_2.pdf](https://github.com/Viindoo/odoo/files/10130472/runbot_merge_upstream_2.pdf)

nó bị lỗi như này,

**Comment by vietphuong97** [comment]
check giúp anh vấn đề Overtime ở lỗi runbot nhé @Theanhngo2905

**Comment by Theanhngo2905** [comment]
@vietphuong10 vâng ạ

**Comment by vietphuong97** [comment]
> Runbot lỗi mà sao vẫn pass hết anh ạ. @royleviindoo
> 
> [runbot_merge_upstream.pdf](https://github.com/Viindoo/odoo/files/10130469/runbot_merge_upstream.pdf) [runbot_merge_upstream_1.pdf](https://github.com/Viindoo/odoo/files/10130471/runbot_merge_upstream_1.pdf) [runbot_merge_upstream_2.pdf](https://github.com/Viindoo/odoo/files/10130472/runbot_merge_upstream_2.pdf)

log runbot

**Comment by royle-vietnam** [comment]
Thay thế bởi https://github.com/Viindoo/odoo/pull/593

**Pull request closed without merging**
